msm: vidc: increase frame-larger-than instead of disabling it
* ubsan wants it to be fixed like that

/home/volight554/nitrogen/kernel/xiaomi/msm8998/drivers/media/platform/msm/vidc/msm_venc.c: In function ‘try_set_ctrl’:
/home/volight554/nitrogen/kernel/xiaomi/msm8998/drivers/media/platform/msm/vidc/msm_venc.c:3760:1: error: the frame size of 2288 bytes is larger than 2048 bytes [-Werror=frame-larger-than=]
 }
 ^